### ISSUE TITLE
Fetch welcome page products and display in Product List

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#13]
As a user, when I open the landing page I want to see a list of sample/promoted products

Technical implementation details:
- Use component created in task #12 
- Get the data from database

Designs:
https://design.penpot.app/#/view/0287358f-ba0f-80b3-8001-af163e079ce3?page-id=aa6c056f-666a-8012-8001-dfd5bc1f9f51&section=interactions&index=1

**Comment by fromITzerotoIThero** [comment]
Hello again! :)

W., I've run into an apparently common error - when checking Response in Network, my devtools keep throwing an error of "You need to enable JavaScript to run this app.".

There seem to be a lot of ways to address it, but since some advice is based on dealing with package.json or config:about (which I have a feeling like it's not good to change), I thought I'd just ask you (in case you've been here) which direction I should go - just very general advice, I'll look up the rest :)

**Comment by piotrwicijowski** [comment]
Latest master branch works fine for me, maybe you could push the changes so that I can see and help you out.

PS - looking at the html document that is the response for the `GET /` network request is always going to look like this, and this is not indicative of any issue or error.

**Comment by fromITzerotoIThero** [comment]
W., stupid me! I've looked at the wrong view! When on `DomainsOverview` everything works just fine, sorry for bothering!

**Comment by fromITzerotoIThero** [comment]
Great then! ;)
