### ISSUE TITLE
Highlight correct header item based on navigation

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#15]
As a user, when I'm on a specific page, I want the top level header navigation to reflect that by highlighting the correct element.

One of the approaches is to use NavLink, as per documentation https://reactrouter.com/en/6.8.0/components/nav-link

**Comment by fromITzerotoIThero** [comment]
Hey Dear Traveller W.!

You need to help me out! 
I've modified the `Header` component so now it uses the `NavLink` element and it kind of works (it does properly add the class `active` when indeed active) but for some reason the grey highlighting bar wouldn't show up. 
I guess it has something to do with CSS selectors but can't figure out what exactly...

**Comment by piotrwicijowski** [comment]
Hi G.

The issue seems to be a bit deeper than that. As it turns out, since version v6 of the react router, the `activeClassName` option is deprecated (see documentation https://reactrouter.com/en/main/components/nav-link ), and in order to achieve the same behavior we have several options:
1. We can still rely on the fact, that `NavLink` sets an `.active` class on the element, but we don't really have any control over that class. Please be aware, that it is just `.active` and not e.g. `.Header_active__Z3r4O` as it would be done by our lovely css modules. So for that we would need to tell our css styles that "this particular style should not be modified in the css modules, unique name per component way". To do so, we can use `:global` modifier. So if you re-write your selector into `.navbar__entry:global.active::after` then it should work. Of course a lot of caution needs to be made, because when using `:global` modifier on the selectors there is a risk of those styles affecting other components, so when you would be using it in the future, make sure that such selector is more specific to the component (e.g. has something like `.navbar__entry` before it).
2. Alternatively, we can apply the advice found here https://stackoverflow.com/a/72471972/10311733 and extract the `isActive` value right in the `className` prop. If you would go that route, you would not need to use `:global` styles (which is nice), but the code would be a bit uglier

Either way, from what I'm seeing, we are slowly running into a bit of code duplication on the level of navbar entry - maybe it could be extracted into its own component?

**Comment by fromITzerotoIThero** [comment]
Oh W., thank you so much for all this advice, I'll dive into it and choose one :)

Argh, I liked this `activeClassName` but they must have good reasons for withdrawing it.  

Whoa, like we should make a `NavBar` entry component because of this ammount of CSS? Sounds like React spirit, I'll do it! :)

**Comment by fromITzerotoIThero** [comment]
Ah! I've read the part of the documentation https://reactrouter.com/en/main/components/nav-link, you provided before, but clearly without understanding, sorry!

**Comment by fromITzerotoIThero** [comment]
W., so I started off with extracting the `NavBarEntry` component and I'm trying to figure out how to deal with the icons, or rather - icon (because I did add an extra one for `Domains` entry for practice, as well as extra `Domain List` entry, but the designs actually don't include it):

- I'm trying to pass the mui icon name as props, but I'm doing something wrong :/

- say we wanted to add an icon to the `Domains` entry as well - does the solution provided [here](https://forum.freecodecamp.org/t/corrent-way-to-pass-material-icons-as-props/460854) would do the job, or is it too complicated for just 2 navbar entries?

**Comment by piotrwicijowski** [comment]
The solution provided in the link looks very bizarre and honestly unreadable. What I would recommend instead, is to pass the icon (as an actual piece of jsx code) instead of passing the icon**Name**. Something like this:
```
<NavBarEntry
    to="/"
    icon={<HomeOutlinedIcon/>}
    entryName="Welcome"
/>
```
Then you can just use that `icon` in your nav bar entry:
```
<NavLink
    to={targetName}
    className={styles.navbar__entry}>
        {icon}
        {entryName}
</NavLink>
```

**Comment by fromITzerotoIThero** [comment]
Oh that looks so good, thx! :D

**Comment by fromITzerotoIThero** [comment]
Sorry for bothering you, but seems like I've killed the navigation in some way... ;P

**Comment by piotrwicijowski** [comment]
Why do you say so? Looks good to me

**Comment by fromITzerotoIThero** [comment]
Oh, now it does, but like a minute ago it wouldn't XP Man... could be internet access issue, that's the only thing that's changed on my computer, sorry again!

**Comment by piotrwicijowski** [comment]
So did you managed to fix the problem you had with `activeClassName` being deprecated? I can see you already moved to new task, but the header is still not highlighting the item

**Comment by fromITzerotoIThero** [comment]
Correct, I haven't finished that one yet, just felt like doing something quite different, so I moved on to the color theming task.

**Comment by fromITzerotoIThero** [comment]
Dear W., 

I wanted to finish up the task and:

1. I decided to go for the second method you suggested (though I have a feeling I might have not understood `extract the isActive value right in the className prop` the way you intended :P)

2. It kind of works (the `NavBarEntry` components know when they are active and it shows in the Inspector), but still the bar isn't there... any hint?

**Comment by piotrwicijowski** [comment]
1. You are pretty close - however the syntax for accessing the `isActive` is a bit different, it needs to be used as such: `className={({isActive}) => ` - notice that it is at the beginning of the `className` prop, and not in the middle (as it is in your code)
2. Once you solve first problem, your second problem will also be solved :)

**Comment by fromITzerotoIThero** [comment]
It did solve the problem, thx! :)

**Comment by fromITzerotoIThero** [comment]
Dear W. :)

So it did take me some time to get down to the tasks but I've learnt a ton of very useful stuff in the meantime and I feel like the programming enlightenment of mine is just so close! :) 

The one here - I closed it as done, however there was one thing not complete - the navbar wouldn't show "active" `Domains` entry when on `DomainDetailsPage`. I thought it could achieve this by nesting `DomainDetailsPage` route within `DomainsOverview` route (because this is actually how IBOS is designed or am I missing something here?) but I'm doing something wrong and I guess it has something to do with the `paths`, would you help me out? :)))

**Comment by piotrwicijowski** [comment]
We can leave it as closed, and get back to it in the future if needed. Let's not focus too much energy here on such small details.

**Comment by fromITzerotoIThero** [comment]
That's what I'll do! :)
