### ISSUE TITLE
Welcome screen

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#2]
Create a `WelcomeScreen` page component:
- Make sure to have separate `pages` directory in `src` to have separate space for components and pages
- Display the `WelcomeScreen` in `App` component
- The text content can be hard-coded
- Styling

Designs: https://design.penpot.app/#/view/0287358f-ba0f-80b3-8001-af163e079ce3?page-id=0287358f-ba0f-80b3-8001-af163e079ce4&section=interactions&index=0

**Comment by fromITzerotoIThero** [comment]
W., I've just started creating the WelcomeScreen component and I have a couple of questions:

1. When adding the component to App.js, should I wrap in a <div>? We did it with the Header component and it looks good to me, but I can't recall exactly why we did that - was it for the sake of adding styles to it with App.module.css? 

2.  Could you give me a hint on which html elements to use in my WelcomeScreen component? Trying to use elements that carry some meaning (like header, main, etc.) instead of <div>s feels right to me, but I'm not sure that's how it should be done.

**Comment by fromITzerotoIThero** [comment]
Oh wow, this communicator doesn't support characters like "<"! The missing text is basically the 'divs' :)

**Comment by piotrwicijowski** [comment]
Hi G.
1. You don't need to wrap the component in a `<div>`, unless you want to add some styles to it from the `App` component level
2. Just use divs and spans for now, let's not bother ourselves with other types of elements for now.

PS. If you want to add code into comments, just click on "add code" icon in the top bar of comment editor ;)

**Comment by fromITzerotoIThero** [comment]
Oh that's a good piece of advice, thx!

**Comment by fromITzerotoIThero** [comment]
W., so I've pretty much completed the WelcomeScreen, still T&E method (including this ugly z-index to prevent the button from appearing in front of the header) - I'll try to move on the next task.

**Comment by fromITzerotoIThero** [comment]
Yeah, so I guess, I'm gonna close this one too ;)
