### ISSUE TITLE
Typescript - add to project

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#30]
- Follow the tutorial here: https://create-react-app.dev/docs/adding-typescript/ on how to add typescript to existing project.
- Do not add any type annotations to any files just yet
- Make sure that the project builds and runs
- Try changing one of the components (e.g. `BasicCard`) from jsx to tsx and see if it builds
- Change the props of that component to a typed object (e.g. here is some tutorial that looks simple enough https://dev.to/typescripttv/typing-react-props-in-typescript-5hal )

**Comment by fromITzerotoIThero** [comment]
Hey W.! 

I've just sat down to this task, I have to go get Radzio now, and I'll only catch the computer in the evening before the meeting. 
I just wanted to signal what issue I've encountered. It's probably not complicated, but just in case it is, here it is: 

I started integrating TS into IBOS and after installing it and changing `BasicCard` extension to .tsx I had this error thrown:

`Compiled with problems:
ERROR
[eslint] 
src\components\BasicCard\BasicCard.tsx
  Line 0:  Parsing error: DeprecationError: 'originalKeywordKind' has been deprecated since v5.0.0 and can no longer be used. Use 'identifierToKeywordKind(identifier)' instead`
  
I figured it has something to do with eslint and its configuration, yet I can't find the .eslintrc file.

**Comment by piotrwicijowski** [comment]
I found a fix for your problems, the change has been pushed to your branch. We can discuss the details later today.

**Comment by piotrwicijowski** [comment]
If you are interested in "how to make the modules css work in react in typescript" here is the stack overflow link https://stackoverflow.com/questions/58380082/create-react-app-typescript-css-modules-auto-generating-type-definitions-wi
