### ISSUE TITLE
Fetch Domain Details including a list of themes

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#7]
Create a supabase query that will fetch all the details for a specific domain:
- The query should be parametrized based on the `id` of the domain
- The result should contain the title and long description of the domain (from the domain's table)
- The result should also contain a list of all themes that is corresponding to the domain (join the domain table with themes table, where theme.domain_id = domain.id)
- *bonus requirement* make sure that fetching all of this data is just one network request that combines both the domain data and themes data

**Comment by fromITzerotoIThero** [comment]
W., 
I need a little (or we'll see about that! XP) help:

1. I'm trying to add styles to `DomainDetails` so it looks like in Penpod, the trouble is, the browser doesn't seem to notice the styles set on the container and I'm wondering why... `<div className={styles.container}>` looks good to me... 

2. I've replaced the empty element `<>` with a `<div>` because I couldn't set a ` className` on it and added `key={theme.id}` to `AccordionElement`s because the console kept throwing some errors (one that didn't break IBOS though) that it should be set - is it ok the way I did it?

**Comment by piotrwicijowski** [comment]
1. You have a typo in your class name in css ;)
2. That's correct, it is not possible to add a class name to `<>`. Your usage of `key` also looks correct :)

**Comment by fromITzerotoIThero** [comment]
XD maaan... I did like a double-typo check before but didn't see it! XD Thank you!!!

**Comment by fromITzerotoIThero** [comment]
Oh I have some more questions :)

I'll turn `DomainDetails` into a page, but for now, I tried to style it as in Penpod and 2 things are bothering me:

1. When data is fetched and put inside of `AccordionElements`, the horizontal bar (that tricky one that was hard to style) of the first element is still there. 
Is it because in this case it doesn't know it's the `first-of-type` for some reason? How should I fix it?

2. The `AccordionElements` and `Accordion` appear on top of the Header when scrolling unlike `BasicCard` components and other fetched data for `DomainDetails` - I suppose it's them to be fixed rather than the Header, but all that's coming to my mind is the z-index which I'd rather not touch.

**Comment by piotrwicijowski** [comment]
1. It no longer is the `first-of-type`, because it has title and details divs before it (and in the end the accordion element's type is `div`, so the style is not applied). Try wrapping just the accordion elements in another div
2. Just slap a `z-index: 1` on the header, and it should work.

**Comment by fromITzerotoIThero** [comment]
Whoa! It works, thx!!! :D
